### ISSUE TITLE
org.sprindoc.demo.app3 BeanUtils.copyProperties method does copy all properties 

### ISSUE THREAD

**Issue by trip2gafa** [springdoc/springdoc-openapi-demos#12]
When I start `org.sprindoc.demo.app3` and post tweet. It gets TweetDTO, and returns Tweet model where id and text are null. 

For example, tweetDto is: 
```
{
  "id": "2",
  "text": "ASDSAS",
  "createdAt": "2020-01-20T10:13:08.650Z"
}. 
```
It will return, tweet model:
```
{
  "id": null,
  "text": null,
  "createdAt": "2020-01-20T10:26:13.589+0000"
}
```

**Comment by bnasslahsen** [comment]
@trip2gafa this a demo app of the generated OpenAPI description.
It's not intended to provide a fully working application from business point of view.
You can propose a PR, if you really want make it better.
