### ISSUE TITLE
How to pass Custom Header in the each Request? and how to show the Custom Header in the Springdoc ui ?

### ISSUE THREAD

**Issue by javaHelper** [springdoc/springdoc-openapi-demos#13]

**Comment by bnasslahsen** [comment]
Closed, as duplicate of https://github.com/springdoc/springdoc-openapi/issues/363

**Comment by javaHelper** [comment]
@bnasslahsen - Thanks for your help so far, however I dont see people are responding to springdoc Open API questions on stackoverflow. Could you please help so that it can be reach to wider people ?
