### ISSUE TITLE
How to serve API spec from multiple services

### ISSUE THREAD

**Issue by tzieleniewski** [springdoc/springdoc-openapi-demos#18]
Hi Team,

We have a API Gateway and we want to serve the documentation for multiple microservices behind it.
We are using Spring Boot 2.2.x.
We tried the springdoc.swagger-ui.urls[0].url but the missing CORS headers block us.
Is there any other way to do that.
May you please point us some other way/example how to achieve that. 

All the best

**Comment by bnasslahsen** [comment]
Hi @tzieleniewski, 

 This is sample code, how to serve multiple microservices behind spring cloud gateway:
- https://github.com/springdoc/springdoc-openapi-demos/tree/master/sample-springdoc-openapi-microservices
