### ISSUE TITLE
Open API Demos upload file error

### ISSUE THREAD

**Issue by mrxccc** [springdoc/springdoc-openapi-demos#26]
I call the example upload interface of 'WebMVC' in Opean API Demos

Link: [uploadFile](https://github.com/springdoc/springdoc-openapi-demos/blob/master/springdoc-openapi-spring-boot-2-webmvc/src/main/java/org/springdoc/demo/app2/api/PetApi.java)

Methods: `uploadFile`

Error message:
![image](https://user-images.githubusercontent.com/50472699/102583814-4a962b80-4140-11eb-8ad6-5694ddd2fdbf.png)

**Comment by bnasslahsen** [comment]
@mrxccc, 


 This is a demo sample...Without any DB or file storage related.

**Comment by Sobhan-Akhavan** [comment]
A request with the header "application/octet-stream" can not parse the file to a multipart file request.

**Comment by Sobhan-Akhavan** [comment]
After changing the consume in postmapping annotation to "multipart/form-data" below all parameter show Send empty value check box.
Is there any way to remove this?
![Screenshot from 2022-09-10 11-20-10](https://user-images.githubusercontent.com/95710538/189472829-d071ad41-e5e0-45fb-8512-c780e298b414.png)
