### ISSUE TITLE
Error 404: springdoc-openapi-demos/sample-springdoc-openapi-oauth2/oauth-resource-server

### ISSUE THREAD

**Issue by katlego-maleka** [springdoc/springdoc-openapi-demos#30]
Good day,

I'm enjoying the sample projects. However, I tried to run this application, it starts correctly however, I'm getting an error 404 when navigating to http://localhost:8081

Your assistance is greatly appreciated.

Kind regards,

**Comment by bnasslahsen** [comment]
@katlego-maleka, 

You can follow the https://github.com/springdoc/springdoc-openapi-demos/blob/master/springdoc-openapi-oauth2/README.md instructions.
