### ISSUE TITLE
Broken dependencies

### ISSUE THREAD

**Issue by Mumeii** [springdoc/springdoc-openapi-demos#34]
Hi

I've cloned this repository today, in order to test the OAuth demo

Unfortunately, this demo is not working anymore. 

The clone have been performed after the latest v3.1.5 release of springdoc-openapi-demos

I've failed starting the authorization server due to a broken dependency between KeyCloak and Liquibase :

- KeyCloak version 11.0.2 is specified by the project's pom, but it's requiring a `getInstance` method in the liquibase `ServiceLocator` class (or interface).
- Unfortunately this `getInstance` method is not available anymore in Liquibase >= 4.x
- It's a Liquibase v4.3.x that the default spring dependencies BOM is pointing to now.

I've tried to specify a Liquibase v3.10.3, the one prior to the problematic 4.x, but doing so lead to other KeyCloak configuration `"missing provider"` troubles, and I'm not familiar at all with KeyCloak, so I can't solve those troubles by myself in a decent amount of time 😝 

Thanks in advance if you find time to update dependencies !

**Comment by bnasslahsen** [comment]
@Mumeii, 

Please use the latest master version. It has been updated.
