### ISSUE TITLE
gateway-service

### ISSUE THREAD

**Issue by 891877295** [springdoc/springdoc-openapi-demos#41]
[gateway-service](https://github.com/springdoc/springdoc-openapi-demos/tree/master/springdoc-openapi-microservices/gateway-service)

```
@Bean
	@Lazy(false)
	public List<GroupedOpenApi> apis(SwaggerUiConfigParameters swaggerUiConfigParameters, RouteDefinitionLocator locator) {
		List<GroupedOpenApi> groups = new ArrayList<>();
		List<RouteDefinition> definitions = locator.getRouteDefinitions().collectList().block();
		for (RouteDefinition definition : definitions) {
			System.out.println("id: " + definition.getId()+ "  "+definition.getUri().toString());
		}
		definitions.stream().filter(routeDefinition -> routeDefinition.getId().matches(".*-service")).forEach(routeDefinition -> {
			String name = routeDefinition.getId().replaceAll("-service", "");
			swaggerUiConfigParameters.addGroup(name);
			GroupedOpenApi.builder().pathsToMatch("/" + name + "/**").group(name).build();
		});
		return groups;
	}

```

groups why not add GroupedOpenApi ?

**Comment by jimmyqin** [comment]
```java
GroupedOpenApi build = GroupedOpenApi.builder()
                    .pathsToMatch("/" + name + "/**")
                    .group(name + "Group")
                    .build();
            groups.add(build);
```

But I need to filter some APIs , to add `addOpenApiMethodFilter( )` method, which doesn't work    
```java
GroupedOpenApi build = GroupedOpenApi.builder()
                    .pathsToMatch("/" + name + "/**")
                     .addOpenApiMethodFilter(method -> method.isAnnotationPresent(Operation.class))
                    .group(name + "Group")
                    .build()
```

**Comment by mmm8955405** [comment]
> ```java
> GroupedOpenApi build = GroupedOpenApi.builder()
>                     .pathsToMatch("/" + name + "/**")
>                     .group(name + "Group")
>                     .build();
>             groups.add(build);
> ```
> 
> 但是我需要过滤一些API来添加`addOpenApiMethodFilter( )`方法，这不起作用
> 
> ```java
> GroupedOpenApi build = GroupedOpenApi.builder()
>                     .pathsToMatch("/" + name + "/**")
>                      .addOpenApiMethodFilter(method -> method.isAnnotationPresent(Operation.class))
>                     .group(name + "Group")
>                     .build()
> ```

I have the same problem. No good examples have been found

**Comment by mmm8955405** [comment]
Compete for the filtering of some APIs, not the whole! No solution found at present
