### ISSUE TITLE
2.x samples

### ISSUE THREAD

**Issue by ch4mpy** [springdoc/springdoc-openapi-demos#49]
**Is your feature request related to a problem? Please describe.**
I have dificulties to migrate my projects to 2.0.0-M6 (security issues)

**Describe the solution you'd like**
I'd like to have spring-boot 3 samples (with web security config and openpi-ui) I could get inspiration from

**Comment by bnasslahsen** [comment]
@ch4mpy,

I have updated the samples here https://github.com/springdoc/springdoc-openapi-demos/tree/2.x/demo-oauth2
