### ISSUE TITLE
springdoc-openapi giving 404 with spring 6

### ISSUE THREAD

**Issue by singps** [springdoc/springdoc-openapi-demos#59]
I am trying to migrate from springfox to  openapi because springfox  swagger2 is not working with Jakarta. I am using spring 6 and followed this https://springdoc.org/v2/ to migrate.  Below are the dependencies added. It is giving me 404 with swagger-ui.html.

<dependency>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
                <version>2.0.4</version>
            </dependency>
            <dependency>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-starter-webmvc-api</artifactId>
                <version>2.0.4</version>
            </dependency>
            <dependency>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-starter-webflux-ui</artifactId>
                <version>2.0.4</version>
            </dependency>

**Comment by krystian-klimek** [comment]
I'm also using a v2 version (2.5.0, 2.6.0) and got 405 with swagger-ui/index.html
