### ISSUE TITLE
How to use SpringDoc to achieve a similar approach in SpringBoot 3

### ISSUE THREAD

**Issue by hongjiahua** [springdoc/springdoc-openapi-demos#62]
![a4ccc8c83f6dc5ea7c2e2c58f1c89576](https://github.com/springdoc/springdoc-openapi-demos/assets/47426264/939b33a4-71a2-49ce-8fb5-01ac6cddda87)

**Comment by bnasslahsen** [comment]
see https://springdoc.org/#migrating-from-springfox
